### ISSUE TITLE
OBS setup creates wrong stream URL

### ISSUE THREAD

**Issue by mstfldmr** [awslabs/amplify-video#177] opened 2020-12-26 03:40 UTC
**Describe the bug**
Script creates wrong stream URL in OBS settings, like **"rtmps://rtmp://IP_ADDRESS:1935/livestream-dev-p"**
The preceding "rtmps://" from the stream server setting of OBS profile should be deleted to be able to start streaming.

**To Reproduce**
`amplify video setup-obs`

**Expected behavior**
create OBS settings correctly.

**Comment by wizage** [comment] 2021-01-07 23:52
duplicate of #155 

We are fixing this in the next release. Holidays got in the way

**Closed by wizage** 2021-01-07 23:52 UTC
