### ISSUE TITLE
VOD - Ask and create a Lambda to perform delete output when a video is removed on input bucket

### ISSUE THREAD

**Issue by yudao** [awslabs/amplify-video#158] opened 2020-11-10 12:47 UTC
**Is your feature request related to a problem? Please describe.**
When we remove a video from the input bucket, it will be nice to have a Lambda function auto generated, and asked Y/n on the ```amplify video add``` command, to perform the deletion of the output render. If yes the lambda is created and attached. If no, no changes from the actual behavior.

**Describe the solution you'd like**
```javascript
 amplify add video
? Please select from one of the below mentioned services: Video On Demand
? Provide a friendly name for your resource to be used as a label for this category in the project: myvodstreams
? Select a system-provided encoding template, specify an already-created template name:  Default HLS Adaptive Bitrate
? Do you want to automatically remove converted output when video input is removed? Y/n
...
```

**Describe alternatives you've considered**
No alternatives. This suggestion follow the [actual architecture with S3 trigger events and Lambda functionalities](https://docs.aws.amazon.com/solutions/latest/video-on-demand-on-aws-foundations/architecture.html).

Thanks for this great plugin!

Yu.

**Comment by yudao** [comment] 2020-11-10 12:50
Sorry duplicate of #106

**Comment by wizage** [comment] 2020-11-15 18:55
Closing for duplicate of #106.

**Closed by wizage** 2020-11-15 18:55 UTC
